### PR TITLE
icon: replace the anki icon

### PR DESCRIPTION
**Pull request by xiaoyifang**

### CODE REVIEW

**Comment by shenlebantongying** [comment]
Maybe we can just use the anki icon instead? https://github.com/ankitects/anki/blob/main/qt/bundle/lin/anki.png

**Comment by shenlebantongying** [comment]
The one from AnkiDroid is svg btw https://github.com/ankidroid/Anki-Android/blob/main/docs/graphics/src/anki.svg

**Comment by shenlebantongying** [comment]
How about this? Steal the blue star from AnkiDroid :sweat_smile:

**Comment by xiaoyifang** [comment]
modified the icon to include both `anki` and `add`

**Comment by tatsumoto-ren** [comment]
Why is the icon so big? I think the old one was perfectly fine. 

screenshot-2024-10-12-18-27-16

**Comment by xiaoyifang** [comment]
I kinda like this one.:-)

**Pull request merged**
