### PR TITLE
clean: simplify loadDictionaries & Initializing dialog's `showInitialy` parameter

### PR DESCRIPTION
**Pull request by shenlebantongying**
Amend https://github.com/xiaoyifang/goldendict-ng/commit/9ae4e57bb8f9ec4625350a2e419444e9752b757e

I honestly cannot tell the difference without the code.

### CODE REVIEW

**Comment by xiaoyifang** [comment]
Initializing Dialog? Isn't this dialog which shows the index processing .
When users open the gd-ng for the first time , it will make headword indexing . All the operations will take time.

**Comment by shenlebantongying** [comment]
The `showInitialy` (which will be passed down to `Initializing` as `showOnStartup`) is always true, except this place:



However, it does nothing because almost immediately, the loading/initializing signals make the dialog to show up.

**Comment by shenlebantongying** [comment]
There is no functional difference before and after, but `loadDictionaries` now don't have a weird `showInitialy` to control the internal dialog's initial state.

Maybe we should move the dialog out of the `loadDictionaries` method so that it can be used without GUI for staff like https://github.com/xiaoyifang/goldendict-ng/discussions/1826

**Comment by xiaoyifang** [comment]
when user choose `start To system Tray`,the mainwindows will be invisible,   showInitialy should = false.

**Pull request merged**
