### PR TITLE
fix: update globalbroadcaster translatelinetext also in scanpopup

### PR DESCRIPTION
**Pull request by MicrochipQ**
Fixes https://github.com/Ajatt-Tools/gd-tools/issues/5

### CODE REVIEW

**Comment by xiaoyifang** [comment]
Can there be a case like this?
On mainwindow search word `A`  ,then on the popup window search word `B`.  then on the mainwindow  `send to anki`.
At the above case ,the last action maybe send `B` instead of `A`

**Comment by xiaoyifang** [comment]
save the searched word in the related articleview ?

**Comment by tatsumoto-ren** [comment]
>  why did you decide to store translateline in globalbroadcaster

If I remember correctly, that was xiaoyifang's idea. https://github.com/xiaoyifang/goldendict-ng/pull/417#issuecomment-1480870293

**Comment by xiaoyifang** [comment]
> > why did you decide to store translateline in globalbroadcaster
> 
> If I remember correctly, that was xiaoyifang's idea. [#417 (comment)](https://github.com/xiaoyifang/goldendict-ng/pull/417#issuecomment-1480870293)

Yes ,it was from me.

I'll accept this PR and try to fix the mentioned issue in the future.

**Pull request merged**
