### PR TITLE
Restructure Source Tree

### PR DESCRIPTION
**Pull request by shenlebantongying**
Can we work together and finish this first before other changes  @xiaoyifang?

Every file is moved, merging conflicts will be too messy.

Don't squash the changes so that git can preserve git blame.

qmake seems to cannot react to some file changes. You may need to remove the build folder and rebuild, cache invalidation :sweat_smile: 

## /src/dict

For every files that contain `Dictionary::MakeDictionaries` plus Dictioanry.cc/.hh and loadDictioanries.cc/.hh

## /src/ui

For every class that is a subclass of `QWidget`

close https://github.com/xiaoyifang/goldendict-ng/issues/503

### CODE REVIEW

**Comment by xiaoyifang** [comment]
> make: *** No rule to make target `icons/macicon.icns', needed by `GoldenDict.app/Contents/Resources/macicon.icns'.  Stop.

**Comment by xiaoyifang** [comment]
> 
GoldenDict_resource.rc(3) : error RC2135 : file not found: D:\a\goldendict-ng\goldendict-ng\icons\programicon.ico

**Comment by shenlebantongying** [comment]
Do we still need CHANGES.md? Just delete it?

**Comment by shenlebantongying** [comment]
result: https://github.com/shenlebantongying/goldendict/tree/work/recrusive_qmake_build

**Comment by xiaoyifang** [comment]
> Do we still need CHANGES.md & conanfile.txt ? Just delete them?

do it

**Comment by xiaoyifang** [comment]
> result: https://github.com/shenlebantongying/goldendict/tree/work/recrusive_qmake_build

LGTM

**Comment by shenlebantongying** [comment]
I think this is pretty much finished. Most of our files are `ui` and `dict` related, the rest are all under `src` directly. Fundamental things like `wstrings.hh` `globalregex` `file.hh` are behind `common`.

image

CMake is no longer usable. Since we are still using Qt5, there is no hurry. I will fix it later :sweat_smile:

**Comment by shenlebantongying** [comment]
I am not sure about the name `common`. It is like `std` or `lib` or `utils` that provides building blocks for true `bussiness logic`, but how `common` is `common` is somehow subjective :sweat_smile:

**Comment by xiaoyifang** [comment]
> I am not sure about the name `common`. It is like `std` or `lib` or `utils` that provides building blocks for true `bussiness logic`, but how `common` is `common` is somehow subjective 😅

should be ok ,we can accept it now ,  if a better reasonable idea come up ,we can change at that time.

**Comment by shenlebantongying** [comment]
Then you can merge this after CI passed :)

**Comment by xiaoyifang** [comment]
Will the translation files still work after rename , maybe need to check.

**Comment by shenlebantongying** [comment]
They should work. The `<location>` is optional

image

**Pull request merged**
