### PR TITLE
opt: when in darkmode ,make the current article more significant

### LINKED ISSUE #493: Dark theme
黑暗模式下,  
词典选取之后的 标记框建议加亮色, 否则不容易看出来;
词义解释的这个框当中, 每部词典的分界色, 也建议增亮;
  .gddictname {
      background-image: initial;
      background-color: rgb(75 75 75);
  }

### PR DESCRIPTION
**Pull request by xiaoyifang**
fix #493

### CODE REVIEW

**Comment by shenlebantongying** [comment]
image
image
The babylon style feels like way too breaking,

**Comment by xiaoyifang** [comment]
in darkreadermode ,I just rotate the dictionary name 2 degree for significant effect 😄

**Comment by xiaoyifang** [comment]
image

**Comment by xiaoyifang** [comment]
only support in modern style right now.

**Pull request merged**
