### PR TITLE
fix: keep the application name unchanged for now

### PR DESCRIPTION
**Pull request by xiaoyifang**

### CODE REVIEW

**Comment by xiaoyifang** [comment]
@shenlebantongying  what do you think?
there are few application path issues related to this.

**Comment by shenlebantongying** [comment]
I think Qt's `applicationName` has too many responsibilities.

Attaching more responsibilities to it only causes more problems.

Maybe we should hardcode the name here:

https://github.com/xiaoyifang/goldendict-ng/blob/67ed24c61c29d4025843c9d892f0445c4c008bde/src/ui/mainwindow.cc#L3105-L3108

**Comment by xiaoyifang** [comment]
Yes ,this is another solution.

**Comment by xiaoyifang** [comment]
changed using your solution

**Pull request merged**
