### PR TITLE
Move none c++ files to sub folders

### PR DESCRIPTION
**Pull request by shenlebantongying**
Related https://github.com/xiaoyifang/goldendict/issues/503

## Move all `.ui` files into `src/ui`

Similar to this project, mix `.ui` and ui related `.cc/.h` files

https://github.com/clementine-player/Clementine/tree/master/src/ui

## Move all `.css` into `src/stylesheets`

The `src/stylesheets/css.qrc` is created because qrc's path is relative to resources's path.

To avoid extra paths (like the `src/qtstyles` in `src/qtstyles/qt-styles.css`), it have to beside the resources.

### CODE REVIEW

**Comment by xiaoyifang** [comment]
nice start ,
I think the restructure the whole project must take a lot of time.
issue #503  can be seperated into multi PRs.

**Comment by xiaoyifang** [comment]
Let me know when you finished

**Comment by shenlebantongying** [comment]
Fixed, this can be merged @xiaoyifang

**Comment by shenlebantongying** [comment]
I will move all files in 1 PR.

**Pull request closed without merging**
