### PR TITLE
fix: dictserver reimplemented with signal

### PR DESCRIPTION
**Pull request by xiaoyifang**

### CODE REVIEW

**Comment by shenlebantongying** [comment]
This reminds me that there are some old code that moves some class declarations to the header files to deal with the `Q_OBJECT` in `.cc` file.

https://github.com/search?q=repo%3Axiaoyifang%2Fgoldendict-ng%20%20%2F%2F%2F%20Exposed%20here%20for%20moc%20&type=code

However, this PR's approach is used by Qt itself and KDE aggressively.

https://github.com/search?q=repo%3Aqt%2Fqtbase+%22.moc%22+language%3AC%2B%2B&type=code&l=C%2B%2B

https://planet.kde.org/friedrich-kossebau-2023-06-28-include-also-moc-files-of-headers/

Maybe we can move the declarations under `/// Exposed here for moc` into their `.cc` and `#include xxxx.moc` too. All related `.hh` under `/sr/dict` will consistently only have `makeDictionaries`.

**Comment by xiaoyifang** [comment]
> This reminds me that there are some old code that moves some class declarations to the header files to deal with the `Q_OBJECT` in `.cc` file.
> 
> https://github.com/search?q=repo%3Axiaoyifang%2Fgoldendict-ng%20%20%2F%2F%2F%20Exposed%20here%20for%20moc%20&type=code
> 
> However, this PR's approach is used by Qt itself and KDE aggressively.
> 
> https://github.com/search?q=repo%3Aqt%2Fqtbase+%22.moc%22+language%3AC%2B%2B&type=code&l=C%2B%2B
> 
> https://planet.kde.org/friedrich-kossebau-2023-06-28-include-also-moc-files-of-headers/
> 
> Maybe we can move the declarations under `/// Exposed here for moc` into their `.cc` and `#include xxxx.moc` too. All related `.hh` under `/sr/dict` will consistently only have `makeDictionaries`.

Can you start a new PR?

**Comment by shenlebantongying** [comment]
Yes, I want to do it this weekend.

**Comment by xiaoyifang** [comment]
in #1338

**Pull request closed without merging**
