### PR TITLE
remove eb.lib and use source directly

### PR DESCRIPTION
**Pull request by xiaoyifang**
Windows version does not work as expected .

the `open` funciton in zio.c   failed with `illegal sequence byte`

some encoding problem?

### CODE REVIEW

**Comment by xiaoyifang** [comment]
@shenlebantongying due to the errors I have found in the simple-eb project,  maybe it is not saft to add it as a submodule in cmakelist.txt for now.

**Comment by shenlebantongying** [comment]
No worries, eb is never enabled on cmake/Windows :sweat_smile:

`-DWITH_FFMPEG_PLAYER=OFF` can disable it in other places.

**Comment by xiaoyifang** [comment]
https://github.com/FooSoft/zero-epwing/blob/master/CMakeLists.txt

@shenlebantongying maybe you can check this about how to embed eb into the project ,it used the eb source code

**Comment by shenlebantongying** [comment]
Cannot we just treat the `/thirdparty/eb` as part of the source code instead of a library?

Compiling to a `library -> link` is a source of frustration because every platform is slightly different.

---

However, since the simple-eb uses cmake too, in theory,

`target_link_libraries(goldendict-ng eb)`

is enough to link it.

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/simple-eb/compare/ec8904dc8b390b746573492806790cd11b164927...f71d7adf69c9feb2ffd4f2e2be7734ba8e9d63d0#diff-6b7bbd985e41024af9c7fb9c4c1feffab8d3fb6ad41af07d376d928728c215d8

Windows can work now ,But I still have no confidence.  the `open` seems can not handle Chinese character.

**Comment by shenlebantongying** [comment]
The `dictzip.c` cannot handle complex filenames on windows too, they used `ufile.cc`, which only compiles on windows, to replace the `open`.

https://github.com/xiaoyifang/goldendict-ng/blob/staged/src/common/ufile.cc

**Pull request merged**
