### PR TITLE
clean: reformat everything and add `.git-blame-ignore-revs`

### PR DESCRIPTION
**Pull request by shenlebantongying**
close https://github.com/xiaoyifang/goldendict-ng/issues/987

* add `.gir-blame-ignore-revs` to avoid overriding 1st level of git blame

Done by `fd -e cc -e hh | xargs clang-format -i --style=file` & `git rev-parse HEAD > .git-blame-ignore-revs 
`

### CODE REVIEW

**Comment by shenlebantongying** [comment]
The CI uses clang-format nightly, which appears to disagree with my local clang-format 16.0
https://github.com/xiaoyifang/goldendict-ng/blob/f97bfc039f1d201a8c2b91f089a153a89157dd55/.github/workflows/auto%20format.yml#L35-L38

**Comment by xiaoyifang** [comment]
> * uncomment `BasedOnStyle: WebKit` to reduce the risk of clang-format version updates.

why? what's the different result? can you illustrate with an example?

**Comment by shenlebantongying** [comment]
> why? what's the different result? can you illustrate with an example?

There is no difference. All options are overwritten, but clang-format might add options in future, this is the future proof.

**Comment by shenlebantongying** [comment]
> why? what's the different result? can you illustrate with an example?
I reverted that change.

**Comment by xiaoyifang** [comment]
the format failed maybe caused by `sudo` permission?

**Comment by xiaoyifang** [comment]
or can keep the `auto format` action as it is .
some minor differences is acceptable.

**Comment by shenlebantongying** [comment]
> or can keep the auto format action as it is .
some minor differences is acceptable.

I am not sure if it is clang-format 17's bug or feature :sweat_smile:

Pinning the current stable version is more robust.

Anyway, the difference is only a new white space.

**Comment by shenlebantongying** [comment]
The git blame is preserved very well  (at least on github's interface)

You can see this on my repo https://github.com/xiaoyifang/goldendict-ng/blame/6e6b3d8876741a65879342617f54ecb6cf0523d2/src/main.cc

**Comment by shenlebantongying** [comment]
Don't squash this merge quest so that .git-blame-ignore-revs would use the correct revision number :)

**Pull request merged**
