### PR TITLE
action: add fcitx5-qt6 im plugin to appimage build

### PR DESCRIPTION
**Pull request by shenlebantongying**
add fcitx support to qt6 appimage build

https://github.com/xiaoyifang/goldendict-ng/issues/795

### CODE REVIEW

**Comment by xiaoyifang** [comment]
you can run the ubuntu6 action manually to test the changes

**Comment by shenlebantongying** [comment]
Yes, almost 10 mins per run. Probably need a few more trials :sweat_smile: .

**Comment by shenlebantongying** [comment]
https://github.com/shenlebantongying/goldendict-ng/actions/runs/5162706859/jobs/9300586304#step:7:1157

**Comment by shenlebantongying** [comment]
Mythical problem: the `libxcb.so` was successfully included before this PR.

Adding this PR's content, the `libxcb.so` will fail to deploy :sweat_smile:

https://github.com/shenlebantongying/goldendict-ng/actions/runs/5162706859/jobs/9300586304#step:7:1156

**Comment by xiaoyifang** [comment]
`Could not find dependency: libxcb-cursor.so.0 `

maybe 
`sudo apt-get install -y libxcb-cursor-dev`

**Comment by shenlebantongying** [comment]
The appimage is built successfully, but the changelog failed and blocks artifact uploading :sweat_smile: 

https://github.com/shenlebantongying/goldendict-ng/actions/runs/5162839803/jobs/9300810123

However, the needed `.so` file appears to be included:

image

**Comment by shenlebantongying** [comment]
I have tested this appiamge, and fcitx works fine for me.

https://github.com/shenlebantongying/goldendict-ng/releases/tag/v23.06.02-alpha.230603.8995a881

This can be merged. @xiaoyifang 

ubuntu20.04 is going to be the minimum stable version of ubuntu until 2025.04. This code will be needed for at least two years :sweat_smile:

**Pull request merged**
