### PR TITLE
actions: revise github workflows

### PR DESCRIPTION
**Pull request by shenlebantongying**
* Add `CMake+vcpkg+Windows` PR check
* Drop `qmake+Windows` PR check
* Drop winlibs PR check
* Tests the Qt version in `ubuntu-24.04` (which is Qt6.4) instead of installing on our own
* Also switch macOS's Qt to homebrew (just for PR check)
* Let macOS build check uses homebrew's ffmpeg instead of building a new one every time, which cost lots of time.
* Use Ninja everywhere,
  * The ubuntu build time reduced from [5mins](https://github.com/xiaoyifang/goldendict-ng/actions/runs/9843689801/job/27175464348) to [2.5 mins](https://github.com/xiaoyifang/goldendict-ng/actions/runs/9844524212/job/27178110869)
* Misc small changes:
  * naming
  * merge install commands into one
  * remove unnecessary installs
  * remove unnecessary setup-python
  * ...

I think we can remove qmake/winlibs now, but there is no hurry.

BTW, can we enable Github's auto-merge? Basically, we can mark a PR to be auto-merged after CI passes. Push or other actions will stop it.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request

### CODE REVIEW

**Comment by xiaoyifang** [comment]
> BTW, can we enable Github's auto-merge? Basically, we can mark a PR to be auto-merged after CI passes.

no auto merge.
As the PR will often get changes after PR passes.

**Comment by shenlebantongying** [comment]
>  As the PR will often get changes after PR passes.

https://discuss.python.org/t/github-auto-merge-is-now-enabled/26176

It adds a button here. "Auto" means "manually" enabling needed.

**Comment by xiaoyifang** [comment]
image

**Comment by xiaoyifang** [comment]
I think If I enable the auto-merge.  take this PR for example ,  this PR will already have got merged.

**Comment by xiaoyifang** [comment]
> It adds a button here. "Auto" means "manually" enabling needed.

I think This only applies to users who have no write permission.

**Comment by xiaoyifang** [comment]
I have enable `Auto-Merge ` option ,  but this PR has no auto-button

**Comment by shenlebantongying** [comment]
Lets me fix the type to trigger the checks, and you can enable auto-merge when the checks is still running.

**Review by xiaoyifang — APPROVED** [review]

**Comment by xiaoyifang** [comment]
image
image

no auto-merge in PR

**Comment by shenlebantongying** [comment]
Ok, I figured it out.

This feature is designed to protect against malicious activities.

A branch protection rule has to be applied to the default branch. (You can also add various other protections to a branch.)

Specifically, for auto-merge, "check status" needs to be specified what actions must be passed before merging.

I will revert build job name changes, then you can add the jobs' names into the rules.

Once those CI passes, auto-merge will happen :)

Screenshot 2024-07-08 a

---

image

----

image

---

image

**Comment by shenlebantongying** [comment]
Let's try auto-merge in another PR, or after we have long-running tests

**Pull request merged**
