### PR TITLE
fix: refresh webview when changed darkreader mode

### PR DESCRIPTION
**Pull request by xiaoyifang**
related #1450

### CODE REVIEW

**Comment by shenlebantongying** [comment]
> black/white screen when switching the darkreader mode.

This thing only happens once, but it fixes the white flashes for everything else like normal refreshing / forward/backward / new word search etc.

**Comment by xiaoyifang** [comment]
> , while fixes all other white flashes like normal refreshing / forward/backward / new word search etc.

The other white flashes are also gone now.

**Comment by xiaoyifang** [comment]
> This black/white screen doesn't even matter because it only happens once,

this is largely due to the slowness of website dictionary.

**Comment by xiaoyifang** [comment]
I'll revert the last commit .no harm to keep it .

**Comment by xiaoyifang** [comment]
A side effect, set the background ,will hide the status bar
image

**Pull request merged**
