### PR TITLE
feat: make initialize ui more human-friendly

### LINKED ISSUE #600: Feature: QSplashScreen with a progressbar instead of the initialize.ui control
**Is your feature request related to a problem? Please describe.**
https://blog.csdn.net/qq_38232598/article/details/95895847
https://www.cnblogs.com/wickhamchen/p/14350081.html
https://blog.csdn.net/baidu_40624101/article/details/125201428
https://doc.qt.io/qt-5/qsplashscreen.html

**Describe the solution you'd like**
display a splashscreen while loading the indexes. check /create new index.

there is a similar PR in https://github.com/goldendict/goldendict/pull/664

### PR DESCRIPTION
**Pull request by xiaoyifang**
fix #600 

QSplashScreen is not used .

the splash.png can be changed in every release.

### CODE REVIEW

**Comment by shenlebantongying** [comment]
The splash screen feels too dark. Where did you get it? It feels like a nightmare 😅

**Comment by xiaoyifang** [comment]
use gimp auto generated .

Can you offer one  :）

**Comment by shenlebantongying** [comment]
How about this:

image

I scratched this in 10 mins (Low budget, but at least better than the auto-generated abomination xD) 

[goldendict.zip](https://github.com/xiaoyifang/goldendict-ng/files/11711983/goldendict.zip)

**Comment by shenlebantongying** [comment]
The image's size is 1600x900. The splash screen should also have a ratio of 16x9 to look perfect.

**Comment by xiaoyifang** [comment]
> The image's size is `1600x900`. To look perfect, the splash screen should also have a ratio of `16x9` (like `800x450`).

I set 680*380

**Comment by shenlebantongying** [comment]
Minor adjustments [goldendict2.zip](https://github.com/xiaoyifang/goldendict-ng/files/11712113/goldendict2.zip)

Mockup with Windows style progress bar and a few numbers:

image

**Comment by xiaoyifang** [comment]
> Minor adjustments [goldendict2.zip](https://github.com/xiaoyifang/goldendict-ng/files/11712113/goldendict2.zip)
> 
> The font used is "Linux Biolinum".
> 
> Mockup with Windows style progress bar and a few numbers:
> 
> image
> 
> Hopefully, a real artist in future can replace this simple PPT-style splash screen 😅

Leave for future improvement.

**Comment by shenlebantongying** [comment]
I mean this version with minor adjustments should be used :)
image

**Pull request merged**
