### PR TITLE
feat: add custom transliteration support

### LINKED ISSUE #661: feature:Add a custom transliteration which can be configured by  users.
**Is your feature request related to a problem? Please describe.**
As required in https://github.com/goldendict/goldendict/issues/1626 ,
https://github.com/goldendict/goldendict/issues/1455

**Describe the solution you'd like**
GoldenDict has a built-in feature called Diacritic which will only to index creation/query.

The custom transliteration is a little different. It will only apply to pre-search phase.to ease the difficult to input certain characters.

**Describe alternatives you've considered**
image

For simplicity,  a textarea can be used .
with each line represent a single transform.

**Additional context**

### PR DESCRIPTION
**Pull request by xiaoyifang**
fix #661

image

image

### CODE REVIEW

**Comment by data-man** [comment]
I can't build GD-ng after this PR.

Fixed by renaming `customtransliteration.cpp` to `customtransliteration.cc`.

**Comment by xiaoyifang** [comment]
do you use cmake to build ?

**Comment by data-man** [comment]
> do you use cmake to build ?

Yes.

**Comment by xiaoyifang** [comment]
got it ,will be fixed .

**Pull request merged**
