### PR TITLE
fix: adjust the order of Mainwindow's show() and restoreState/restoreGeometry

### PR DESCRIPTION
**Pull request by shenlebantongying**
Not sure if it is a bug in Qt.

close https://github.com/xiaoyifang/goldendict-ng/issues/1048

The `translateLine->setFocus();` is deleted because it is overridden later by the code inside `if ( !cfg.preferences.enableTrayIcon || !cfg.preferences.startToTray ) {`

After the show()/restoreState()/restoreGeometry(), no new widgets related to the main window will be created.

### CODE REVIEW

**Comment by xiaoyifang** [comment]
When the mainwindow is maximized,  it can not restore the left docker's width.

**Comment by xiaoyifang** [comment]
maximized the mainwindow , then quit.

After restart it can not restore the left docker's width.

**Comment by shenlebantongying** [comment]
> maximized the mainwindow , then quit.
>
> After restart it can not restore the left docker's width.

Cannot reproduce


https://github.com/xiaoyifang/goldendict-ng/assets/20123683/b46b198c-e6c2-484d-91cc-f469153f5540

**Comment by xiaoyifang** [comment]
I can reproduce it on Windows.

**Pull request merged**
