### PR TITLE
feat!: add libzim dependency

### LINKED ISSUE #671: rewrite the logic of zim parse
**Is your feature request related to a problem? Please describe.**
Current goldendict has implemented its own zim dictionary parse logic.

**Describe the solution you'd like**
- [x] replace it with libzim #725 
- [ ] reuse the fulltext in libzim which will save a lot of disk space.
libzim does not support CJK search correctly until version 8.2.0+ .  I think this implementation should wait.

### PR DESCRIPTION
**Pull request by xiaoyifang**
relates to #671 

This is a **breaking change**
-----------

Introduce Libzim package.

Linux distributions should install a more recent libzim package to have this work. or install libzim from source.
the default libzim4-dev on Ubuntu20 does not work.   

---------------------

Some features introduced in this PR.

1. reduce the index file size,  

for a 1.6G zim dictionary , the previous index file is about 80M.  now only 25M is needed.  
meanwhile the cost of time to create the index also reduced .
The memory consumption is about 600M at most

2. only use url as headword when title is empty.

this will reduce the headword about 1/2 of its previous implementation. Goldendict's is designed for dictionaries,  the zim is for website ,use url as headword does not feel correct.

3. hide the headword when display the content.

the reason is same as the above ,  headword is not proper to display as the content most likely is website html.

-------------------

Some bugs fixed by the way.

https://github.com/xiaoyifang/goldendict-ng/pull/725#issuecomment-1560263460

### CODE REVIEW

**Comment by xiaoyifang** [comment]
@shenlebantongying  can you help to fix the cmake  error on Ubuntu and Macos ,

**Comment by shenlebantongying** [comment]
Adding this line should fix the problem. Two paths are added, becuase M1 & intel macOS install packages to different locations.
```bash
export PKG_CONFIG_PATH=/opt/homebrew/opt/icu4c/lib/pkgconfig:/usr/local/opt/icu4c/lib/pkgconfig:"$PKG_CONFIG_PATH"
```

The macOS already provides icu, homebrew don't want to mess that up, so it is not exposed by default.

**Comment by xiaoyifang** [comment]
fix the audio issue mentioned in[ this issue](https://github.com/goldendict/goldendict/issues/1599) by the way.



https://github.com/xiaoyifang/goldendict-ng/assets/105986/d91258a8-fefc-423d-8b2d-35c406a4185c

**Pull request merged**
