### PR TITLE
[Win]: remove ffmpeg winlibs

### PR DESCRIPTION
**Pull request by xiaoyifang**
relate #1165

### CODE REVIEW

**Comment by atauzki** [comment]
the two xapian cmake config file are wrongly removed in the first commit.

**Comment by atauzki** [comment]
these two files seems to be wronly removed.
image

**Comment by xiaoyifang** [comment]
> these two files seems to be wrongly removed.

xapian cmake files do not have any use.

**Comment by xiaoyifang** [comment]
> And the libvorbis dependency of lsa dict may also be removed by refactor the code. FFMpeg also supports it.

This can be left for the next PR.  
the vorbis dependencies is not mixed with ffmpeg .  Currently I just remove the `CONFIG+=no_ffmpeg_player `

**Pull request merged**
